In [1]:
#numpy : numerical python
import numpy as np


In [2]:
# create an object class
arr1 = np.array([54, 65,98,78])
print(arr1)

[54 65 98 78]


In [ ]:
# To check the dimension of an array
arr1.ndim

In [4]:
# To check the shape
arr1.shape

(4,)

In [5]:
# To know the data type
arr1.dtype

dtype('int64')

In [7]:
arr2 = np.array([[78,95,96,32], [45,65,32,14]])
print(arr2)

[[78 95 96 32]
 [45 65 32 14]]


dtype('int64')

In [8]:
arr2.ndim



2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr2.dtype

dtype('int64')

In [11]:
np.linspace(15, 150)

array([ 15.        ,  17.75510204,  20.51020408,  23.26530612,
        26.02040816,  28.7755102 ,  31.53061224,  34.28571429,
        37.04081633,  39.79591837,  42.55102041,  45.30612245,
        48.06122449,  50.81632653,  53.57142857,  56.32653061,
        59.08163265,  61.83673469,  64.59183673,  67.34693878,
        70.10204082,  72.85714286,  75.6122449 ,  78.36734694,
        81.12244898,  83.87755102,  86.63265306,  89.3877551 ,
        92.14285714,  94.89795918,  97.65306122, 100.40816327,
       103.16326531, 105.91836735, 108.67346939, 111.42857143,
       114.18367347, 116.93877551, 119.69387755, 122.44897959,
       125.20408163, 127.95918367, 130.71428571, 133.46938776,
       136.2244898 , 138.97959184, 141.73469388, 144.48979592,
       147.24489796, 150.        ])

In [13]:
np.linspace(15, 150, 20)

array([ 15.        ,  22.10526316,  29.21052632,  36.31578947,
        43.42105263,  50.52631579,  57.63157895,  64.73684211,
        71.84210526,  78.94736842,  86.05263158,  93.15789474,
       100.26315789, 107.36842105, 114.47368421, 121.57894737,
       128.68421053, 135.78947368, 142.89473684, 150.        ])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((4,5), dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
np.arange(15,106)

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105])

In [23]:
np.arange(15,106,3)

array([ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42,  45,  48,  51,
        54,  57,  60,  63,  66,  69,  72,  75,  78,  81,  84,  87,  90,
        93,  96,  99, 102, 105])

In [24]:
arr3 = np.random.randint(10,90,100)
print(arr3)

[78 60 17 13 49 36 63 83 79 28 33 40 78 66 42 86 19 43 53 86 22 48 26 35
 88 82 23 72 39 28 79 38 51 40 66 65 82 24 54 34 24 40 24 81 67 85 76 48
 16 43 87 82 46 53 55 32 65 86 68 42 22 44 56 44 53 42 79 30 58 61 51 57
 53 65 46 13 85 70 52 79 79 53 87 58 40 20 14 43 14 76 36 22 49 50 85 72
 41 22 86 19]


In [31]:
np.random.seed(8)
arr3 = np.random.randint(10,90,100)
print(arr3)

[77 15 18 73 58 70 59 84 37 23 19 71 25 69 28 24 66 19 61 78 63 63 81 69
 52 36 76 19 25 73 41 30 55 31 82 38 57 20 74 17 55 12 48 81 46 70 78 47
 76 48 64 49 56 16 42 83 17 19 52 29 69 58 19 26 88 65 65 30 34 16 38 15
 76 29 85 21 56 82 65 24 49 25 29 68 53 25 38 42 51 26 84 43 76 80 72 17
 18 44 51 55]


In [30]:
arr4 =arr3.reshape(10,10)
print(arr4)

[[77 15 18 73 58 70 59 84 37 23]
 [19 71 25 69 28 24 66 19 61 78]
 [63 63 81 69 52 36 76 19 25 73]
 [41 30 55 31 82 38 57 20 74 17]
 [55 12 48 81 46 70 78 47 76 48]
 [64 49 56 16 42 83 17 19 52 29]
 [69 58 19 26 88 65 65 30 34 16]
 [38 15 76 29 85 21 56 82 65 24]
 [49 25 29 68 53 25 38 42 51 26]
 [84 43 76 80 72 17 18 44 51 55]]


In [33]:
print(arr4[4,4])

46


In [35]:
arr5 = arr4.flatten()
print(arr5)

[77 15 18 73 58 70 59 84 37 23 19 71 25 69 28 24 66 19 61 78 63 63 81 69
 52 36 76 19 25 73 41 30 55 31 82 38 57 20 74 17 55 12 48 81 46 70 78 47
 76 48 64 49 56 16 42 83 17 19 52 29 69 58 19 26 88 65 65 30 34 16 38 15
 76 29 85 21 56 82 65 24 49 25 29 68 53 25 38 42 51 26 84 43 76 80 72 17
 18 44 51 55]


In [36]:
np.sum(arr5)

np.int64(4871)

In [37]:
np.max(arr5)

np.int32(88)

In [38]:
np.min(arr5)

np.int32(12)

In [39]:
np.mean(arr5)

np.float64(48.71)

In [40]:
np.median(arr5)

np.float64(50.0)

In [41]:
np.std(arr5)

np.float64(22.516791512113798)

In [42]:
np.var(arr5)

np.float64(507.00590000000005)

In [46]:
np.percentile(arr5, 45)

np.float64(46.550000000000004)

In [47]:
np.sqrt(arr5)

array([8.77496439, 3.87298335, 4.24264069, 8.54400375, 7.61577311,
       8.36660027, 7.68114575, 9.16515139, 6.08276253, 4.79583152,
       4.35889894, 8.42614977, 5.        , 8.30662386, 5.29150262,
       4.89897949, 8.1240384 , 4.35889894, 7.81024968, 8.83176087,
       7.93725393, 7.93725393, 9.        , 8.30662386, 7.21110255,
       6.        , 8.71779789, 4.35889894, 5.        , 8.54400375,
       6.40312424, 5.47722558, 7.41619849, 5.56776436, 9.05538514,
       6.164414  , 7.54983444, 4.47213595, 8.60232527, 4.12310563,
       7.41619849, 3.46410162, 6.92820323, 9.        , 6.78232998,
       8.36660027, 8.83176087, 6.8556546 , 8.71779789, 6.92820323,
       8.        , 7.        , 7.48331477, 4.        , 6.4807407 ,
       9.11043358, 4.12310563, 4.35889894, 7.21110255, 5.38516481,
       8.30662386, 7.61577311, 4.35889894, 5.09901951, 9.38083152,
       8.06225775, 8.06225775, 5.47722558, 5.83095189, 4.        ,
       6.164414  , 3.87298335, 8.71779789, 5.38516481, 9.21954

In [48]:
# to know the index of the max value
np.argmax(arr5)

np.int64(64)

In [49]:
# index of min
np.argmin(arr5)

np.int64(41)